/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MINEDUCYT
 */
public class Calculadora extends javax.swing.JFrame {

    public float N1 = 0;
    public float N2 = 0;
    public String Operador;
    int igual = 0;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();

        setResizable(false);
        setTitle("Calculadora");
        this.setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/img/Calculadora.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));

        LabelWallpaper.setIcon(icon);

        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonLimpiar = new javax.swing.JButton();
        ButtonDividir = new javax.swing.JButton();
        ButtonMultiplicar = new javax.swing.JButton();
        ButtonSumar = new javax.swing.JButton();
        ButtonMenos = new javax.swing.JButton();
        ButtonIgual = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        ButtonPunto = new javax.swing.JButton();
        TxtPantalla = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        TxtAnterior = new javax.swing.JTextField();
        TxtOperador = new javax.swing.JTextField();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculadora");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonLimpiar.setBackground(new java.awt.Color(56, 56, 56));
        ButtonLimpiar.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        ButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLimpiar.setText("c");
        ButtonLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 60));

        ButtonDividir.setBackground(new java.awt.Color(56, 56, 56));
        ButtonDividir.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        ButtonDividir.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDividir.setText("/");
        ButtonDividir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDividirActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, 60));

        ButtonMultiplicar.setBackground(new java.awt.Color(56, 56, 56));
        ButtonMultiplicar.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        ButtonMultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMultiplicar.setText("x");
        ButtonMultiplicar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 70, 60));

        ButtonSumar.setBackground(new java.awt.Color(56, 56, 56));
        ButtonSumar.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        ButtonSumar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonSumar.setText("+");
        ButtonSumar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSumarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 70, 130));

        ButtonMenos.setBackground(new java.awt.Color(56, 56, 56));
        ButtonMenos.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        ButtonMenos.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMenos.setText("-");
        ButtonMenos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenosActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 70, 60));

        ButtonIgual.setBackground(new java.awt.Color(56, 56, 56));
        ButtonIgual.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        ButtonIgual.setForeground(new java.awt.Color(255, 255, 255));
        ButtonIgual.setText("=");
        ButtonIgual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIgualActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 70, 130));

        Button0.setBackground(new java.awt.Color(56, 56, 56));
        Button0.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button0.setForeground(new java.awt.Color(255, 255, 255));
        Button0.setText("0");
        Button0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });
        getContentPane().add(Button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 150, 60));

        Button1.setBackground(new java.awt.Color(56, 56, 56));
        Button1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.setText("1");
        Button1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 70, 60));

        Button2.setBackground(new java.awt.Color(56, 56, 56));
        Button2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button2.setForeground(new java.awt.Color(255, 255, 255));
        Button2.setText("2");
        Button2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        getContentPane().add(Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 70, 60));

        Button3.setBackground(new java.awt.Color(56, 56, 56));
        Button3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button3.setForeground(new java.awt.Color(255, 255, 255));
        Button3.setText("3");
        Button3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        getContentPane().add(Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 70, 60));

        Button4.setBackground(new java.awt.Color(56, 56, 56));
        Button4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button4.setForeground(new java.awt.Color(255, 255, 255));
        Button4.setText("4");
        Button4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });
        getContentPane().add(Button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 70, 60));

        Button5.setBackground(new java.awt.Color(56, 56, 56));
        Button5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button5.setForeground(new java.awt.Color(255, 255, 255));
        Button5.setText("5");
        Button5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });
        getContentPane().add(Button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 70, 60));

        Button6.setBackground(new java.awt.Color(56, 56, 56));
        Button6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button6.setForeground(new java.awt.Color(255, 255, 255));
        Button6.setText("6");
        Button6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });
        getContentPane().add(Button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 70, 60));

        Button8.setBackground(new java.awt.Color(56, 56, 56));
        Button8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button8.setForeground(new java.awt.Color(255, 255, 255));
        Button8.setText("8");
        Button8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });
        getContentPane().add(Button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 70, 60));

        Button7.setBackground(new java.awt.Color(56, 56, 56));
        Button7.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button7.setForeground(new java.awt.Color(255, 255, 255));
        Button7.setText("7");
        Button7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });
        getContentPane().add(Button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 70, 60));

        Button9.setBackground(new java.awt.Color(56, 56, 56));
        Button9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Button9.setForeground(new java.awt.Color(255, 255, 255));
        Button9.setText("9");
        Button9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });
        getContentPane().add(Button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 70, 60));

        ButtonPunto.setBackground(new java.awt.Color(56, 56, 56));
        ButtonPunto.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        ButtonPunto.setForeground(new java.awt.Color(255, 255, 255));
        ButtonPunto.setText(".");
        ButtonPunto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 70, 60));

        TxtPantalla.setBackground(new java.awt.Color(255, 255, 255));
        TxtPantalla.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        TxtPantalla.setForeground(new java.awt.Color(56, 56, 56));
        TxtPantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TxtPantalla.setOpaque(true);
        getContentPane().add(TxtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 290, 60));

        BtnVolver.setText("Volver");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 10, 75, -1));

        TxtAnterior.setEditable(false);
        TxtAnterior.setBackground(new java.awt.Color(56, 56, 56));
        TxtAnterior.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TxtAnterior.setForeground(new java.awt.Color(255, 255, 255));
        TxtAnterior.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtAnterior.setBorder(null);
        getContentPane().add(TxtAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 30));

        TxtOperador.setEditable(false);
        TxtOperador.setBackground(new java.awt.Color(56, 56, 56));
        TxtOperador.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TxtOperador.setForeground(new java.awt.Color(255, 255, 255));
        TxtOperador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtOperador.setBorder(null);
        getContentPane().add(TxtOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 40, 30));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed

        if (igual == 0) {
            this.TxtPantalla.setText(this.TxtPantalla.getText() + "0");
        } else {
            this.TxtPantalla.setText("0");
            igual = 0;
        }

    }//GEN-LAST:event_Button0ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed

        if (igual == 0) {
            this.TxtPantalla.setText(this.TxtPantalla.getText() + "1");
        } else {
            this.TxtPantalla.setText("1");
            igual = 0;
        }

    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed

        if (igual == 0) {
            this.TxtPantalla.setText(this.TxtPantalla.getText() + "2");
        } else {
            this.TxtPantalla.setText("2");
            igual = 0;
        }

    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed

        if (igual == 0) {
            this.TxtPantalla.setText(this.TxtPantalla.getText() + "3");
        } else {
            this.TxtPantalla.setText("3");
            igual = 0;
        }

    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed

        if (igual == 0) {
            this.TxtPantalla.setText(this.TxtPantalla.getText() + "4");
        } else {
            this.TxtPantalla.setText("4");
            igual = 0;
        }

    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed

        if (igual == 0) {
            this.TxtPantalla.setText(this.TxtPantalla.getText() + "5");
        } else {
            this.TxtPantalla.setText("5");
            igual = 0;
        }

    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed

        if (igual == 0) {
            this.TxtPantalla.setText(this.TxtPantalla.getText() + "6");
        } else {
            this.TxtPantalla.setText("6");
            igual = 0;
        }

    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed

        if (igual == 0) {
            this.TxtPantalla.setText(this.TxtPantalla.getText() + "7");
        } else {
            this.TxtPantalla.setText("7");
            igual = 0;
        }

    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed

        if (igual == 0) {
            this.TxtPantalla.setText(this.TxtPantalla.getText() + "8");
        } else {
            this.TxtPantalla.setText("8");
            igual = 0;
        }

    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed

        if (igual == 0) {
            this.TxtPantalla.setText(this.TxtPantalla.getText() + "9");
        } else {
            this.TxtPantalla.setText("9");
            igual = 0;
        }

    }//GEN-LAST:event_Button9ActionPerformed

    private void ButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarActionPerformed

        this.TxtPantalla.setText("");
        this.N1 = 0;
        this.N2 = 0;
        this.Operador = "";
        TxtOperador.setText(Operador);
        TxtAnterior.setText("");
        igual = 0;

    }//GEN-LAST:event_ButtonLimpiarActionPerformed

    private void ButtonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSumarActionPerformed

        if (TxtAnterior.getText().isEmpty()) {
            this.N1 = Float.parseFloat(this.TxtPantalla.getText());
        } else {
            Operacion();
        }
        TxtAnterior.setText(Resultado(this.N1));
        this.Operador = "+";
        TxtOperador.setText(Operador);
        this.TxtPantalla.setText("");

    }//GEN-LAST:event_ButtonSumarActionPerformed

    private void ButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIgualActionPerformed

        Operacion();
        TxtPantalla.setText(Resultado(this.N1));
        TxtAnterior.setText("");
        TxtOperador.setText("");
        N1 = 0;
        N2 = 0;
        igual = 1;

    }//GEN-LAST:event_ButtonIgualActionPerformed

    private void ButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDividirActionPerformed

        if (TxtAnterior.getText().isEmpty()) {
            this.N1 = Float.parseFloat(this.TxtPantalla.getText());
        } else {
            Operacion();
        }
        TxtAnterior.setText(Resultado(this.N1));
        this.Operador = "/";
        TxtOperador.setText(Operador);
        this.TxtPantalla.setText("");

    }//GEN-LAST:event_ButtonDividirActionPerformed

    private void ButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMultiplicarActionPerformed

        if (TxtAnterior.getText().isEmpty()) {
            this.N1 = Float.parseFloat(this.TxtPantalla.getText());
        } else {
            Operacion();
        }
        TxtAnterior.setText(Resultado(this.N1));
        this.Operador = "x";
        TxtOperador.setText(Operador);
        this.TxtPantalla.setText("");

    }//GEN-LAST:event_ButtonMultiplicarActionPerformed

    private void ButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenosActionPerformed

        if (TxtAnterior.getText().isEmpty()) {
            this.N1 = Float.parseFloat(this.TxtPantalla.getText());
        } else {
            Operacion();
        }
        TxtAnterior.setText(Resultado(this.N1));
        this.Operador = "-";
        TxtOperador.setText(Operador);
        this.TxtPantalla.setText("");

    }//GEN-LAST:event_ButtonMenosActionPerformed

    private void ButtonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPuntoActionPerformed

        if (igual == 0) {
            if (!TxtPantalla.getText().isEmpty()) {
                if (!this.TxtPantalla.getText().contains(".")) {
                    this.TxtPantalla.setText(this.TxtPantalla.getText() + ".");
                }
            } else {
                this.TxtPantalla.setText(this.TxtPantalla.getText() + "0.");
            }
        } else {
            this.TxtPantalla.setText("0.");
            igual = 0;
        }

    }//GEN-LAST:event_ButtonPuntoActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    public void Operacion() {
        
        if (this.TxtAnterior.getText().isEmpty()) {
            return;
        }
        
        if (this.TxtPantalla.getText().isEmpty()) {
            return;
        }
        
        this.N2 = Float.parseFloat(this.TxtPantalla.getText());
        if (this.Operador.equals("+")) {
            this.N1 = this.N1 + this.N2;
        } else if (this.Operador.equals("-")) {
            this.N1 = this.N1 - this.N2;
        } else if (this.Operador.equals("/")) {

            if (N2 == 0) {
                JOptionPane.showMessageDialog(null, "Error: No fue posible dividir por cero.");
            } else {
                this.N1 = this.N1 / this.N2;
            }

        } else if (this.Operador.equals("x")) {
            this.N1 = this.N1 * this.N2;
        }
        TxtPantalla.setText(Resultado(this.N1));
        TxtAnterior.setText("");
        this.Operador = "";
        TxtOperador.setText(Operador);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVolver;
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonDividir;
    private javax.swing.JButton ButtonIgual;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JButton ButtonMenos;
    private javax.swing.JButton ButtonMultiplicar;
    private javax.swing.JButton ButtonPunto;
    private javax.swing.JButton ButtonSumar;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextField TxtAnterior;
    private javax.swing.JTextField TxtOperador;
    private javax.swing.JLabel TxtPantalla;
    // End of variables declaration//GEN-END:variables

    public String Resultado(float total) {
        return (total % 1 == 0) ? Integer.toString((int) total) : Float.toString(total);
    }
}
