/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MINEDUCYT
 */
public class Encontrar extends javax.swing.JFrame {

    DefaultTableModel intento = new DefaultTableModel();
    int x = 0;
    int num = 0;
    int ban = 0;
    Random ran = new Random();

    public Encontrar() {
        initComponents();

        this.setLocationRelativeTo(null);

        num = ran.nextInt(100) + 1;

        intento.addColumn("Intento");
        intento.addColumn("Estado");
        intento.addColumn("Numero");

        TableIntentos.setModel(intento);
        TableIntentos.setEnabled(false);
        jScrollPane1.setOpaque(false); 
        jScrollPane1.getViewport().setOpaque(false);  
        jScrollPane1.setBorder(null);

        ImageIcon wallpaper = new ImageIcon("src/img/Encontrar.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));

        LabelWallpaper.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableIntentos = new javax.swing.JTable();
        TxtRespuesta = new javax.swing.JTextField();
        BtnEnviar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnVolver1 = new javax.swing.JButton();
        TxtResultado = new javax.swing.JTextField();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableIntentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Intentos", "Numeros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableIntentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 6, 220, 320));

        TxtRespuesta.setBackground(new java.awt.Color(56, 56, 56));
        TxtRespuesta.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TxtRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        TxtRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtRespuesta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, 57));

        BtnEnviar.setBackground(new java.awt.Color(56, 56, 56));
        BtnEnviar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEnviar.setText("Enviar");
        BtnEnviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 80, 57));

        jButton1.setBackground(new java.awt.Color(56, 56, 56));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reinicio");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 70, 57));

        BtnVolver1.setText("Volver");
        BtnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolver1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 75, -1));

        TxtResultado.setEditable(false);
        TxtResultado.setBackground(new java.awt.Color(56, 56, 56));
        TxtResultado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TxtResultado.setForeground(new java.awt.Color(255, 255, 255));
        TxtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtResultado.setText("Estoy pensando un numero entre 1 y 100");
        TxtResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, 350, 40));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnviarActionPerformed
        if (ban == 0) {
            String input = TxtRespuesta.getText();

            if (input.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un valor.");
                return;
            }

            if (intento.getRowCount() >= 18) {
                intento.removeRow(0);
            }

            try {
                int resp = Integer.parseInt(input);

                if (resp < num) {
                    TxtResultado.setText("El número en el que pienso es más alto que " + resp);
                    x++;
                    Object[] nuevaFila = {x, "Mayor", resp};
                    intento.addRow(nuevaFila);
                    TxtRespuesta.setText("");
                } else if (resp > num) {
                    TxtResultado.setText("El número en el que pienso es más bajo que " + resp);
                    x++;
                    Object[] nuevaFila = {x, "Menor", resp};
                    intento.addRow(nuevaFila);
                    TxtRespuesta.setText("");
                } else {
                    ban = 1;
                    x++;
                    TxtResultado.setText("Felicidades el numero era el " + resp + ", Numero de Intentos: " + x);
                    Object[] nuevaFila = {x, "Era el", resp};
                    intento.addRow(nuevaFila);
                    TxtRespuesta.setText("");
                    TxtRespuesta.setEditable(false);
                    BtnEnviar.setEnabled(false);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Solo se aceptan números.");
                TxtRespuesta.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El número ya fue adivinado, reinicie la partida.");
            TxtRespuesta.setText("");
        }

    }//GEN-LAST:event_BtnEnviarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Reinicio();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolver1ActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encontrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encontrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encontrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encontrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encontrar().setVisible(true);
            }
        });
    }

    public void Reinicio() {
        while (intento.getRowCount() > 0) {
            intento.removeRow(0);
        }

        TxtRespuesta.setEditable(true);
        BtnEnviar.setEnabled(true);
        ban = 0;
        x = 0;
        TxtRespuesta.setText("");
        num = ran.nextInt(100) + 1;

        TxtResultado.setText("Estoy Pensando un numero entre 1 y 100");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnviar;
    private javax.swing.JButton BtnVolver1;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTable TableIntentos;
    private javax.swing.JTextField TxtRespuesta;
    private javax.swing.JTextField TxtResultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
