/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author MINEDUCYT
 */
public class Inicio extends javax.swing.JFrame {

    int ID = 1;
    OpcionVentana[] opcionesVentanas = {
        new OpcionVentana("Calculadora", "Calculadora sencilla", "src/img/Calculadora.jpg", "src/img/calculadoraIcon.png", Calculadora.class),
        new OpcionVentana("Conversor", "Conversor de unidades", "src/img/Medidas.jpg", "src/img/medidasIcon.png", Conversor.class),
        new OpcionVentana("Cara o Cruz", "Lanza una moneda al aire", "src/img/Coin.jpg", "src/img/coinIco.png", Moneda.class),
        new OpcionVentana("Visualizador", "Visualizador de HTML", "src/img/Visualizador.jpg", "src/img/visualizadorIco.png", Visualizador.class),
        new OpcionVentana("Encuentra", "Adivina el numero que genero la pc", "src/img/Encontrar.jpg", "src/img/encontrarIco.png", Encontrar.class),
        new OpcionVentana("Repetidor", "Repite una frase muechas veces", "src/img/Repetir.jpg", "src/img/Repetir.png", Repetidor.class),
        new OpcionVentana("Paletas", "Arma paletas de colores", "src/img/Paleta.jpg", "src/img/paleta.png", Paletas.class),
        new OpcionVentana("MathMixer", "Funciones matematicas", "src/img/Mathmixer.jpg", "src/img/mathmiexer.png", MathMixer.class),
        new OpcionVentana("Información de la app", "Notas de Versión", "src/img/Info.jpg", "", Info.class)
    };

    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarBoton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAccion = new javax.swing.JButton();
        BtnRetroceder = new javax.swing.JButton();
        BtnAvanzar = new javax.swing.JButton();
        TxtDescripcion = new javax.swing.JTextField();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAccion.setBackground(new java.awt.Color(52, 52, 52));
        BtnAccion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnAccion.setForeground(new java.awt.Color(255, 255, 255));
        BtnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAccionActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 270, 169));

        BtnRetroceder.setBackground(new java.awt.Color(52, 52, 52));
        BtnRetroceder.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        BtnRetroceder.setForeground(new java.awt.Color(255, 255, 255));
        BtnRetroceder.setText("<");
        BtnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 60));

        BtnAvanzar.setBackground(new java.awt.Color(52, 52, 52));
        BtnAvanzar.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        BtnAvanzar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAvanzar.setText(">");
        BtnAvanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAvanzarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAvanzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 130, 60));

        TxtDescripcion.setEditable(false);
        TxtDescripcion.setBackground(new java.awt.Color(52, 52, 52));
        TxtDescripcion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TxtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        TxtDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtDescripcion.setText("Descripcion de la app");
        TxtDescripcion.setBorder(null);
        getContentPane().add(TxtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 30));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAccionActionPerformed
        if (ID >= 1 && ID <= opcionesVentanas.length) {
            OpcionVentana opcion = opcionesVentanas[ID - 1];
            this.dispose();
            try {
                JFrame nuevaVentana = (JFrame) opcion.getVentanaClase().getDeclaredConstructor().newInstance();
                nuevaVentana.setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            throw new IllegalArgumentException("ID no válido: " + ID);
        }
    }//GEN-LAST:event_BtnAccionActionPerformed

    private void BtnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetrocederActionPerformed
        if (ID > 1) {
            ID -= 1;
        } else {
            ID = opcionesVentanas.length;
        }
        actualizarBoton();
    }//GEN-LAST:event_BtnRetrocederActionPerformed

    private void BtnAvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAvanzarActionPerformed
        if (ID < opcionesVentanas.length) {
            ID += 1;
        } else {
            ID = 1;
        }
        actualizarBoton();
    }//GEN-LAST:event_BtnAvanzarActionPerformed

    private void actualizarBoton() {
        if (ID >= 1 && ID <= opcionesVentanas.length) {
            BtnAccion.setText(opcionesVentanas[ID - 1].getNombre());
            TxtDescripcion.setText(opcionesVentanas[ID - 1].getDescripcion());
            this.setTitle(opcionesVentanas[ID - 1].getNombre());

            ImageIcon wallpaper = new ImageIcon(opcionesVentanas[ID - 1].getWallpaper());
            Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                    LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));

            LabelWallpaper.setIcon(icon);

            ImageIcon botonIcono = new ImageIcon(opcionesVentanas[ID - 1].getIcon());
            Icon iconoEscalado = new ImageIcon(botonIcono.getImage().getScaledInstance(
                    60, 60, Image.SCALE_DEFAULT));

            BtnAccion.setIcon(iconoEscalado);
        } else {
            throw new IllegalArgumentException("ID no válido: " + ID);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    public class OpcionVentana {

        private String nombre;
        private String descripcion;
        private String wallpaper;
        private String icon;
        private Class<?> ventanaClase;

        public OpcionVentana(String nombre, String descripción, String wallpaper, String icon, Class<?> ventanaClase) {
            this.nombre = nombre;
            this.descripcion = descripción;
            this.wallpaper = wallpaper;
            this.icon = icon;
            this.ventanaClase = ventanaClase;
        }

        public String getNombre() {
            return nombre;
        }

        public String getDescripcion() {
            return descripcion;
        }

        public String getWallpaper() {
            return wallpaper;
        }

        public String getIcon() {
            return icon;
        }

        public Class<?> getVentanaClase() {
            return ventanaClase;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAccion;
    private javax.swing.JButton BtnAvanzar;
    private javax.swing.JButton BtnRetroceder;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextField TxtDescripcion;
    // End of variables declaration//GEN-END:variables
}
