/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author MINEDUCYT
 */
public class Repetidor extends javax.swing.JFrame {

    int y = 0;
    int x = 0;
    String Frase;

    public Repetidor() {
        initComponents();

        this.setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/img/Repetir.jpg");
        Icon icon = new ImageIcon(wallpaper.getImage().getScaledInstance(LabelWallpaper.getWidth(),
                LabelWallpaper.getHeight(), Image.SCALE_DEFAULT));

        LabelWallpaper.setIcon(icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtFrase = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        TxtRepetir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaFraseRepetida = new javax.swing.JTextArea();
        TxtEstado = new javax.swing.JTextField();
        BtnVolver1 = new javax.swing.JButton();
        LabelWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtFrase.setBackground(new java.awt.Color(56, 56, 56));
        TxtFrase.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtFrase.setForeground(new java.awt.Color(255, 255, 255));
        TxtFrase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtFrase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 40));

        jButton1.setBackground(new java.awt.Color(56, 56, 56));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Repetir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 90, 40));

        TxtRepetir.setBackground(new java.awt.Color(56, 56, 56));
        TxtRepetir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtRepetir.setForeground(new java.awt.Color(255, 255, 255));
        TxtRepetir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtRepetir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtRepetir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 90, 40));

        AreaFraseRepetida.setEditable(false);
        AreaFraseRepetida.setBackground(new java.awt.Color(56, 56, 56));
        AreaFraseRepetida.setColumns(20);
        AreaFraseRepetida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AreaFraseRepetida.setForeground(new java.awt.Color(255, 255, 255));
        AreaFraseRepetida.setLineWrap(true);
        AreaFraseRepetida.setRows(5);
        AreaFraseRepetida.setText("Este repetidor puede repetir hasta 800 veces una frase\n\nEscribe @N para que se reemplace con números en orden.");
        AreaFraseRepetida.setWrapStyleWord(true);
        AreaFraseRepetida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(AreaFraseRepetida);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 520, 280));

        TxtEstado.setEditable(false);
        TxtEstado.setBackground(new java.awt.Color(56, 56, 56));
        TxtEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtEstado.setForeground(new java.awt.Color(255, 255, 255));
        TxtEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(TxtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 520, 40));

        BtnVolver1.setText("Volver");
        BtnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolver1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 75, -1));
        getContentPane().add(LabelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Frase = TxtFrase.getText();
        String fraseModificada = "";
        x = Integer.parseInt(TxtRepetir.getText());
        y = 0;
        StringBuilder fraseRepetida = new StringBuilder();

        if (x < 801 && x > 0) {
            TxtEstado.setText("Repitiendo Frase, esto puede tomar un momento");
            while (y < x) {
                fraseModificada = Frase.replace("@N", String.valueOf(y + 1));
                if (y != (x - 1)) {
                    fraseRepetida.append(fraseModificada).append("\n");
                } else {
                    fraseRepetida.append(fraseModificada);
                }
                y++;
            }
            AreaFraseRepetida.setText(fraseRepetida.toString());
            TxtEstado.setText("Frase repetida con éxito");
        } else {
            TxtEstado.setText("No es posible repetir ese numero de vece");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolver1ActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Repetidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Repetidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Repetidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Repetidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Repetidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaFraseRepetida;
    private javax.swing.JButton BtnVolver1;
    private javax.swing.JLabel LabelWallpaper;
    private javax.swing.JTextField TxtEstado;
    private javax.swing.JTextField TxtFrase;
    private javax.swing.JTextField TxtRepetir;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
